### ISSUE TITLE
Getting element of nested inner map causes unreachable error

### ISSUE THREAD

**Issue by stocks29** [ash-project/reactor#206]
**Describe the bug**
When trying to fetch the element() within a nested map, an unreachable error occurs

**To Reproduce**
Here is a simple test which causes this error: https://github.com/stocks29/reactor/commit/977379eba972a5c82f1adbc9bb57bdc49ac39d82

**Expected behavior**
I would expect the inner element to be populated in the argument and no unreachable error

**Runtime**
 - Elixir version: 1.18.2
 - Erlang version: 27.2.4
 - OS: MacOS
 - Spark version: 2.2.52

**Additional context**

```
  1) test it nested maps over it's inputs (Reactor.Dsl.MapTest)
     test/reactor/dsl/map_test.exs:65
     ** (Reactor.Error.Invalid)
     Invalid Error

     * # Run Step Error

     An error occurred while attempting to run the `{Reactor.Step.Map, :map_over_numbers, :map_over_numbers_inner, 0}` step.

     ## `step`:

     %Reactor.Step{arguments: [%Reactor.Argument{description: nil, name: :source, source: %Reactor.Template.Value{value: [0, 2], sub_path: []}, transform: nil}, %Reactor.Argument{description: nil, name: :multiplier, source: %Reactor.Template.Value{value: 2, sub_path: []}, transform: nil}], async?: false, context: %{}, description: nil, impl: {Reactor.Step.Map, [return: :double, state: :init, steps: [%Reactor.Step{arguments: [%Reactor.Argument{description: nil, name: :input, source: %Reactor.Template.Element{name: :map_over_numbers_inner, sub_path: []}, transform: nil}], async?: true, context: %{}, description: nil, impl: {Reactor.Step.AnonFn, [run: &Reactor.Dsl.MapTest.NestedMapOverNumbersReactor.run_0_generated_B3889487949762C3504B9351586B2938/2, compensate: nil, undo: nil]}, name: :double, max_retries: :infinity, ref: :double, transform: nil, guards: []}], allow_async?: false, batch_size: 100]}, name: {Reactor.Step.Map, :map_over_numbers, :map_over_numbers_inner, 0}, max_retries: 0, ref: {Reactor.Step.Map, :map_over_numbers, :map_over_numbers_inner, 0}, transform: nil, guards: []}

     ## `error`:

     # Unreachable Error

     You should _never_ see this error in the wild. If you do please raise an issue on
     the Reactor repository:

         https://github.com/ash-project/reactor/issues/new

     And paste the following information:

     --- BEGIN COPY ---

     Reached unreachable code at /Users/bob/projects/reactor/lib/reactor/step/map.ex:295:

     Attempted to retrieve an element whose source doesn't match the current map step: :map_over_numbers_inner vs {Reactor.Step.Map, :map_over_numbers, :map_over_numbers_inner, 0}

     Bindings:

       - `:argument`: `%Reactor.Argument{description: nil, name: :input, source: %Reactor.Template.Element{name: :map_over_numbers_inner, sub_path: []}, transform: nil}`
       - `:descendant_step_names`: `MapSet.new([:double])`
       - `:element`: `0`
       - `:index`: `0`
       - `:map_step`: `%Reactor.Step{arguments: [%Reactor.Argument{description: nil, name: :source, source: %Reactor.Template.Value{value: [0, 2], sub_path: []}, transform: nil}, %Reactor.Argument{description: nil, name: :multiplier, source: %Reactor.Template.Value{value: 2, sub_path: []}, transform: nil}], async?: false, context: %{}, description: nil, impl: {Reactor.Step.Map, [return: :double, state: :init, steps: [%Reactor.Step{arguments: [%Reactor.Argument{description: nil, name: :input, source: %Reactor.Template.Element{name: :map_over_numbers_inner, sub_path: []}, transform: nil}], async?: true, context: %{}, description: nil, impl: {Reactor.Step.AnonFn, [run: &Reactor.Dsl.MapTest.NestedMapOverNumbersReactor.run_0_generated_B3889487949762C3504B9351586B2938/2, compensate: nil, undo: nil]}, name: :double, max_retries: :infinity, ref: :double, transform: nil, guards: []}], allow_async?: false, batch_size: 100]}, name: {Reactor.Step.Map, :map_over_numbers, :map_over_numbers_inner, 0}, max_retries: 0, ref: {Reactor.Step.Map, :map_over_numbers, :map_over_numbers_inner, 0}, transform: nil, guards: []}`
       - `:step`: `%Reactor.Step{arguments: [%Reactor.Argument{description: nil, name: :input, source: %Reactor.Template.Element{name: :map_over_numbers_inner, sub_path: []}, transform: nil}], async?: true, context: %{}, description: nil, impl: {Reactor.Step.AnonFn, [run: &Reactor.Dsl.MapTest.NestedMapOverNumbersReactor.run_0_generated_B3889487949762C3504B9351586B2938/2, compensate: nil, undo: nil]}, name: :double, max_retries: :infinity, ref: :double, transform: nil, guards: []}`

     Backtrace:

         (reactor 0.15.2) lib/reactor/utils.ex:74: anonymous fn/3 in Reactor.Utils.map_while_ok/3
         (reactor 0.15.2) lib/reactor/utils.ex:145: anonymous fn/3 in Reactor.Utils.reduce_while_ok/3
         (elixir 1.18.2) lib/enum.ex:4964: Enumerable.List.reduce/3
         (elixir 1.18.2) lib/enum.ex:2600: Enum.reduce_while/3
         (reactor 0.15.2) lib/reactor/step/map.ex:291: Reactor.Step.Map.rewrite_arguments/4
         (reactor 0.15.2) lib/reactor/step/map.ex:264: Reactor.Step.Map.rewrite_step_for_element/6
         (reactor 0.15.2) lib/reactor/utils.ex:74: anonymous fn/3 in Reactor.Utils.map_while_ok/3
         (reactor 0.15.2) lib/reactor/utils.ex:145: anonymous fn/3 in Reactor.Utils.reduce_while_ok/3
         (elixir 1.18.2) lib/enum.ex:4964: Enumerable.List.reduce/3
         (elixir 1.18.2) lib/enum.ex:2600: Enum.reduce_while/3
         (reactor 0.15.2) lib/reactor/step/map.ex:220: anonymous fn/7 in Reactor.Step.Map.steps_for_batch/3
         (reactor 0.15.2) lib/reactor/utils.ex:145: anonymous fn/3 in Reactor.Utils.reduce_while_ok/3
         (elixir 1.18.2) lib/enum.ex:4964: Enumerable.List.reduce/3
         (elixir 1.18.2) lib/enum.ex:2600: Enum.reduce_while/3
         (reactor 0.15.2) lib/reactor/step/map.ex:180: Reactor.Step.Map.do_emit_batch/5
         (reactor 0.15.2) lib/reactor/executor/step_runner.ex:160: Reactor.Executor.StepRunner.do_run/4
         (reactor 0.15.2) lib/reactor/executor/step_runner.ex:51: Reactor.Executor.StepRunner.run/4


     System:

       Elixir  (175c824) compiled with Erlang/OTP 25
       Erlang/OTP 27.2.4 [erts-15.2.2]
       Darwin Bobs-MacBook-Pro.local 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:16 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6000 arm64


     Running applications:

       - hex 2.1.1
       - telemetry 1.3.0
       - public_key 1.17.1
       - mime 2.0.6
       - ex_check 0.16.0
       - iex 1.18.2
       - libgraph 0.16.0
       - crypto 5.5.2
       - glob_ex 0.1.11
       - credo 1.7.11
       - elixir 1.18.2
       - ex_unit 1.18.2
       - decimal 2.3.0
       - ham 0.3.0
       - ex_doc 0.37.3
       - git_cli 0.3.0
       - sobelow 0.13.0
       - eex 1.18.2
       - nimble_parsec 1.4.2
       - inflex 2.1.0
       - mimic 1.11.2
       - yaml_elixir 2.11.0
       - spitfire 0.2.0
       - erts 15.2.2
       - git_ops 2.7.2
       - finch 0.19.0
       - yamerl 0.10.0
       - file_system 1.1.0
       - mint 1.7.1
       - reactor 0.15.2
       - compiler 8.5.5
       - jason 1.4.4
       - syntax_tools 3.2.1
       - owl 0.12.2
       - igniter 0.5.45
       - nimble_pool 1.1.0
       - tools 4.1.1
       - ymlr 5.1.3
       - splode 0.2.9
       - bunt 1.0.0
       - rewrite 1.1.2
       - stdlib 6.2
       - sourceror 1.8.2
       - dialyzer 5.3.1
       - mix 1.18.2
       - makeup_erlang 1.0.2
       - ssl 11.2.8
       - req 0.5.10
       - mix_test_watch 1.2.0
       - iterex 0.1.2
       - makeup 1.2.1
       - spark 2.2.49
       - doctor 0.22.0
       - asn1 5.3.1
       - text_diff 0.1.0
       - erlex 0.2.7
       - hpax 1.0.3
       - earmark_parser 1.4.43
       - makeup_elixir 1.0.1
       - logger 1.18.2
       - inets 9.3.2
       - kernel 10.2.2
       - nimble_options 1.1.1
       - dialyxir 1.4.5
       - mix_audit 2.1.4

     --- END COPY ---

     Please carefully read all of the above and redact any sensitive information.
```
